// vectorstore/chroma.client.js
// -----------------------------------------------------------------------------
// WHY THIS FILE EXISTS
// A single, lazily-initialized ChromaDB collection handle shared across the
// app, wired to LangChain's Chroma vector store wrapper + Ollama embeddings.
// Keeping this separate from rag.service.js means the *storage engine* can
// be swapped (e.g. for Qdrant or pgvector) without touching RAG logic.
// -----------------------------------------------------------------------------
import { Chroma } from '@langchain/community/vectorstores/chroma';
import { OllamaEmbeddings } from '@langchain/ollama';
import { config } from '../config/index.js';

let storeInstance = null;

/**
 * Returns a cached Chroma vector store bound to the configured embedding
 * model and collection. Because embeddings are generated by a *local*
 * Ollama model (nomic-embed-text by default), no data ever leaves the
 * machine — that's the whole point of "local AI chat".
 */
export async function getVectorStore() {
  if (storeInstance) return storeInstance;

  const embeddings = new OllamaEmbeddings({
    model: config.settings.embedModel,
    baseUrl: config.ollamaBaseUrl,
  });

  storeInstance = await Chroma.fromExistingCollection(embeddings, {
    collectionName: config.chromaCollection,
    url: config.chromaUrl,
  }).catch(async () => {
    // Collection doesn't exist yet (first run) — create it empty.
    return Chroma.fromDocuments([], embeddings, {
      collectionName: config.chromaCollection,
      url: config.chromaUrl,
    });
  });

  return storeInstance;
}

/** Forces recreation of the cached store (used after embedding model changes). */
export function resetVectorStoreCache() {
  storeInstance = null;
}
